module.exports = Object.freeze({
  ROLE_LOCATION_MANAGER: 1,
  ROLE_USER: 2,
  ROLE_ADMIN: 3,

  TIME_REPLY_APPROVAL: 600,

  NOTIFICATION_TYPE_MESSAGE: '1',
  NOTIFICATION_TYPE_UPVOTE: '2',
  NOTIFICATION_TYPE_DOWNVOTE: '3',
  NOTIFICATION_TYPE_REPORT: '4',

  SYSTEM_RATE_PERCENT: 0.5,

  PUBLIC_LOCATION : 1,
  PRIVATE_LOCATION: 2
});